{% set name = "panedr" %}
{% set version = "0.7.0" %}
{% set sha256 = "ef1f3163cd88ff5d69f9aabc1e5850a47cc5325d8421e57510bfa7cae5956838" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
requirements:
  host:
    - python
    - setuptools
    - pip
    - pbr
  run:
    - python
    - pandas
    - pbr

test:
  imports:
    - panedr

about:
  home: http://github.com/jbarnoud/panedr
  license: LGPL-2.1
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: GROMACS edr files to pandas dataframe
  description: |
    Panedr reads a Gromacs EDR file and returns its content as a pandas dataframe. The library 
    exposes one function—the edr_to_df function—that gets the path to an EDR file and returns a
    pandas dataframe.
  doc_url: http://github.com/jbarnoud/panedr
  dev_url: http://github.com/jbarnoud/panedr

extra:
  recipe-maintainers:
    - orbeckst
    - richardjgowers
    - ialibay
    - kain88-de
    - jbarnoud
