{% set name = "panedr" %}
{% set version = "0.8.0" %}
{% set sha256 = "50ecac36810d12db77903048b4972a234b6e3b2c122ffa2a158eba0ff69effc4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
    - pbr
  run:
    - python >=3.6
    - pandas
    - pbr
    - pyedr =={{ version }}

test:
  imports:
    - panedr
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/jbarnoud/panedr
  license: LGPL-2.1-or-later
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: GROMACS edr files to pandas dataframe
  description: |
    Panedr reads a Gromacs EDR file and returns its content as a pandas dataframe. The library 
    exposes one function—the edr_to_df function—that gets the path to an EDR file and returns a
    pandas dataframe.
  doc_url: http://github.com/jbarnoud/panedr
  dev_url: http://github.com/jbarnoud/panedr

extra:
  recipe-maintainers:
    - orbeckst
    - richardjgowers
    - ialibay
    - kain88-de
    - jbarnoud
